language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: H73KX6u626vbP2deRqLWHI50SFX3B5cm0mCpzKMeoIAj/L6eMM5WC111IIXu9Q+HSW38ktZdKSpUO7c4KYBh1/1dDVCyOxCVi2vu/dmFQgb6X2cZIucR2lW+XKeYHA9dMllYvclPhrLHh9Yl9GrcEc73AcLTsYRWkZWQBciHe0G4klhrAfIEO8FESRI6Q/4ahsSkxYUUlsrrGtD9gzBje+faOwhLx8f3QqmzIyaxptqbHOHY9Z+3qqm407g28yqkd/u4Ulb+E0XLReiFV2XF29VKD/6kSHOYz6puWVPypu+6trrMu+7lYaaIxEhZ7sT3/D3oamI1IXzGF2qCtatkVlqigqg9R/o3evfOJVIi555NTMgrWfWKxGeRm1AMbmvDzjK/fNIutK47iE9dWFeyJRhc7LJgyriHSQ4tzE0l0p5cp76/+bxZMgPK1v3GyHYo7SxynDx4r8uAPmArHwvoty2p1L1BARpkP8liBXZt7eKDtMLee8XuXBaAQZralzqMNrsaCXDQwK26DlzTuYF1UHje0YYPrLIrSBFDEBV0jqHDHOp+u4e6QUB33gIcm66fOadvLp9uemtiu22oBygTrIGzN5uTKG6H0PGBy2ZzR8SVmNyqCQB09DEtX39mspKnYvYbQ0nIJT6uJRS/O4BRBrbDWTd8JyGAcWOUOTbhtKI=
  on:
    tags: true
    branches: true
