language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
before_deploy:
- mkdir -p deploy/packager/latest
- mkdir -p deploy/packager/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- cp *.sh deploy/packager/latest
- cp *.sh deploy/packager/${TRAVIS_TAG:-$TRAVIS_COMMIT}
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: CT+yckqgdWsunGsU2/R5mFUfQg9OO/YGaqHgvYJvkFPVuOzeTUGPlTsgCK0rWw4DbrorQrXhehzILa5nQFuQ1U66KjyxvbRVDcZPtzQ+W0UfWIf+9pUgiaRnxj8SqP1EGSTdxBuMX+ne0y6fBzyzmYb7QQvB4k9hGfWvAYKhOiKCINaaOwxBagGeZhDlR4L0wnePcSpJtzAbDGMiG/2FS3DyrknJm0RrS3WCmn7xjSQQsilpR8ppVxl9Y+OC6YiH9Fh2g6nsWInEdTGYCHy8U/5ss+MMzfKxkJbBYDzyrJJVg/FVAKQcrWU1JqAy9mGvH5XLXdAMUeekZAVTitnNraFfL2f/Is7f5IrzCMhNmjugt3tk/L7NLMA43GZTVxvsCofCodyyqLMawcjToZYINNdN8sEv/oTnbhT1xyAOEBVhDeMuHNMfs3pN0CqILtDujUKUCiWYzqGm+oqpFL/0yap7fsta1O5tGXial3iDtfmWDF8vG99Du4UmUpxsJXIXeFXVIb8qBtjbQT4KqN3V869HsaF3flFIa1flqVI0iNDNUOUEYkiHehidEL9Od/Fy5yndTqHD/wbEmq9ELJPIYYJpUW5ydmGRfLDitMZLCOg7A6vyD2G0nONO6GxRKZ6iUN1BB7t8qdmO0tDUd+OKTFsy2A0TgmzjkUgNpR0pM3o=
  bucket: meshblu-connector
  local-dir: deploy
  upload-dir: tools
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: H73KX6u626vbP2deRqLWHI50SFX3B5cm0mCpzKMeoIAj/L6eMM5WC111IIXu9Q+HSW38ktZdKSpUO7c4KYBh1/1dDVCyOxCVi2vu/dmFQgb6X2cZIucR2lW+XKeYHA9dMllYvclPhrLHh9Yl9GrcEc73AcLTsYRWkZWQBciHe0G4klhrAfIEO8FESRI6Q/4ahsSkxYUUlsrrGtD9gzBje+faOwhLx8f3QqmzIyaxptqbHOHY9Z+3qqm407g28yqkd/u4Ulb+E0XLReiFV2XF29VKD/6kSHOYz6puWVPypu+6trrMu+7lYaaIxEhZ7sT3/D3oamI1IXzGF2qCtatkVlqigqg9R/o3evfOJVIi555NTMgrWfWKxGeRm1AMbmvDzjK/fNIutK47iE9dWFeyJRhc7LJgyriHSQ4tzE0l0p5cp76/+bxZMgPK1v3GyHYo7SxynDx4r8uAPmArHwvoty2p1L1BARpkP8liBXZt7eKDtMLee8XuXBaAQZralzqMNrsaCXDQwK26DlzTuYF1UHje0YYPrLIrSBFDEBV0jqHDHOp+u4e6QUB33gIcm66fOadvLp9uemtiu22oBygTrIGzN5uTKG6H0PGBy2ZzR8SVmNyqCQB09DEtX39mspKnYvYbQ0nIJT6uJRS/O4BRBrbDWTd8JyGAcWOUOTbhtKI=
  on:
    tags: true
